name: CLI Build on Main (GoReleaser)

on:
  push:
    branches:
      - main # Trigger this workflow on every push to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux runner for building
    permissions:
      contents: read # Only read permission is needed as we are not creating a release.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code.

      - name: Set up Go
        uses: actions/setup-go@v5 # Action to set up the Go environment.
        with:
          go-version: '1.25.1' # Using a stable Go version.

      # The 'Create dist directory' and 'Get build info for ldflags' steps are no longer needed,
      # as goreleaser handles these internally.

      - name: Run GoReleaser (Snapshot Build)
        uses: goreleaser/goreleaser-action@v5 # Action to run GoReleaser.
        with:
          distribution: goreleaser # Use the goreleaser binary.
          version: latest # Use the latest version of goreleaser.
          args: build --snapshot --clean # Build a snapshot (dev build) and clean up.
          workdir: ./cli_app # <--- IMPORTANT: Run goreleaser from the cli_app directory.
        env:
          # Pass the API Key from GitHub Secrets as an environment variable to goreleaser.
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # GoReleaser automatically provides .Version, .Commit, .Date based on git info.
          # No need to manually set these as environment variables unless you want to override.

      - name: Upload built binaries as artifacts
        uses: actions/upload-artifact@v4 # Action to upload workflow artifacts.
        with:
          # GoReleaser places artifacts in a 'dist' directory relative to its working directory.
          # Since goreleaser runs in './cli_app', the 'dist' directory will be './cli_app/dist'.
          name: cslab-binaries-${{ github.sha }} # Name of the artifact, includes commit SHA for uniqueness.
          path: ./cli_app/dist/ # Path to the directory containing the binaries.
          retention-days: 7 # Keep artifacts for 7 days.